<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.icij</groupId>
  <artifactId>intellij-code-formatter</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <ide.version>2025.3.1</ide.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>app</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/app.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>util</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/util.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>util_rt</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/util_rt.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>util-8</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/util-8.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>lib</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/lib.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>jps-model</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/jps-model.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.libraries.fastutil</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.libraries.fastutil.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.libraries.kotlinx.collections.immutable</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.libraries.kotlinx.collections.immutable.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.libraries.guava</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.libraries.guava.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>opentelemetry</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/opentelemetry.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.regexp</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.regexp.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.parser</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.parser.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.psi</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.psi.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.psi.impl</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.psi.impl.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.analysis</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.analysis.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.analysis.impl</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.analysis.impl.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.impl</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.impl.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.ui.common</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.ui.common.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>module-intellij.xml.syntax</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/lib/module-intellij.xml.syntax.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>java-impl</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/java/lib/java-impl.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>java-impl-frontend</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/java/lib/java-impl-frontend.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>Groovy</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/Groovy/lib/Groovy.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>properties</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/properties/lib/properties.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>yaml</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/yaml/lib/yaml.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>json</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/json/lib/json.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>kotlin-plugin</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/Kotlin/lib/kotlin-plugin.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>kotlin-plugin-shared</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/Kotlin/lib/kotlin-plugin-shared.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>downloaded-intellij-jar</groupId>
      <artifactId>kotlinc.kotlin-compiler-common</artifactId>
      <version>${ide.version}</version>
      <scope>system</scope>
      <systemPath>${project.build.directory}/ide/plugins/Kotlin/lib/kotlinc.kotlin-compiler-common.jar</systemPath>
    </dependency>

    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.8.10</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core</artifactId>
      <version>1.6.4</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>annotations</artifactId>
      <version>24.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.intellij.deps</groupId>
      <artifactId>trove4j</artifactId>
      <version>1.0.20200330</version>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>2.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-1.2-api</artifactId>
      <version>2.20.0</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml</groupId>
      <artifactId>aalto-xml</artifactId>
      <version>1.3.3</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-serialization-core</artifactId>
      <version>1.5.1</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-serialization-json</artifactId>
      <version>1.5.1</version>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.30</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.9.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>intellij-code-formatter</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <compilerArgs>
            <arg>--add-exports</arg>
            <arg>java.base/sun.nio.ch=ALL-UNNAMED</arg>
            <arg>--add-exports</arg>
            <arg>java.base/jdk.internal.misc=ALL-UNNAMED</arg>
          </compilerArgs>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.30</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>

      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.9.0</version>
        <executions>
          <execution>
            <id>download-idea</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>https://download-cdn.jetbrains.com/idea/idea-${ide.version}.win.zip</url>
              <outputDirectory>${project.build.directory}/idea-downloads</outputDirectory>
              <outputFileName>idea-${ide.version}.win.zip</outputFileName>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>extract-idea-jars</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <unzip src="${project.build.directory}/idea-downloads/idea-${ide.version}.win.zip"
                       dest="${project.build.directory}/ide">
                  <patternset>
                    <include name="lib/app.jar"/>
                    <include name="lib/util.jar"/>
                    <include name="lib/util_rt.jar"/>
                    <include name="lib/util-8.jar"/>
                    <include name="lib/lib.jar"/>
                    <include name="lib/jps-model.jar"/>
                    <include name="lib/module-intellij.libraries.fastutil.jar"/>
                    <include name="lib/module-intellij.libraries.kotlinx.collections.immutable.jar"/>
                    <include name="lib/module-intellij.libraries.guava.jar"/>
                    <include name="lib/opentelemetry.jar"/>
                    <include name="lib/module-intellij.regexp.jar"/>
                    <include name="lib/module-intellij.xml.parser.jar"/>
                    <include name="lib/module-intellij.xml.psi.jar"/>
                    <include name="lib/module-intellij.xml.psi.impl.jar"/>
                    <include name="lib/module-intellij.xml.analysis.jar"/>
                    <include name="lib/module-intellij.xml.analysis.impl.jar"/>
                    <include name="lib/module-intellij.xml.impl.jar"/>
                    <include name="lib/module-intellij.xml.ui.common.jar"/>
                    <include name="lib/module-intellij.xml.syntax.jar"/>
                    <include name="plugins/java/lib/java-impl.jar"/>
                    <include name="plugins/java/lib/java-impl-frontend.jar"/>
                    <include name="plugins/Groovy/lib/Groovy.jar"/>
                    <include name="plugins/properties/lib/properties.jar"/>
                    <include name="plugins/yaml/lib/yaml.jar"/>
                    <include name="plugins/json/lib/json.jar"/>
                    <include name="plugins/Kotlin/lib/kotlin-plugin.jar"/>
                    <include name="plugins/Kotlin/lib/kotlin-plugin-shared.jar"/>
                    <include name="plugins/Kotlin/lib/kotlinc.kotlin-compiler-common.jar"/>
                  </patternset>
                </unzip>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.7.0</version>
        <executions>
          <execution>
            <id>unpack-system-scope-jars</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
              <includeScope>system</includeScope>
              <outputDirectory>${project.build.outputDirectory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>com.intellij.formatter.JetbrainsFormatterApplication</mainClass>
                  <manifestEntries>
                    <Multi-Release>true</Multi-Release>
                  </manifestEntries>
                </transformer>
              </transformers>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>**/*.png</exclude>
                    <exclude>**/*.gif</exclude>
                    <exclude>**/*.jpg</exclude>
                    <exclude>**/*.svg</exclude>
                    <exclude>**/*.ico</exclude>
                    <exclude>**/*.ttf</exclude>
                    <exclude>**/*.otf</exclude>
                    <exclude>**/*.woff</exclude>
                    <exclude>**/*.woff2</exclude>
                    <exclude>images/**</exclude>
                    <exclude>expui/**</exclude>
                    <exclude>fonts/**</exclude>
                    <exclude>tips/**</exclude>
                    <exclude>darwin/**</exclude>
                    <exclude>win32/**</exclude>
                    <exclude>linux/**</exclude>
                    <exclude>native/**</exclude>
                    <exclude>com/sun/jna/**</exclude>
                    <exclude>com/intellij/debugger/**</exclude>
                    <exclude>com/intellij/coverage/**</exclude>
                    <exclude>com/intellij/execution/**</exclude>
                    <exclude>org/apache/xmlgraphics/**</exclude>
                    <exclude>org/apache/batik/**</exclude>
                    <exclude>com/intellij/diff/**</exclude>
                    <exclude>com/intellij/vcs/**</exclude>
                    <exclude>com/intellij/openapi/vcs/**</exclude>
                    <exclude>org/intellij/plugins/markdown/**</exclude>
                    <exclude>org/toml/**</exclude>
                    <exclude>dictionary/**</exclude>
                    <exclude>com/intellij/documentation/mdn/**</exclude>
                    <exclude>META-INF/native/**</exclude>
                    <exclude>org/apache/pdfbox/**</exclude>
                    <exclude>org/apache/fontbox/**</exclude>
                    <exclude>org/bouncycastle/**</exclude>
                    <exclude>io/grpc/**</exclude>
                    <exclude>search/**</exclude>
                    <exclude>org/apache/lucene/**</exclude>
                    <exclude>net/jpountz/**</exclude>
                    <exclude>tables/**</exclude>
                    <exclude>mozilla/**</exclude>
                    <exclude>io/ktor/**</exclude>
                    <exclude>kotlinx/html/**</exclude>
                    <exclude>openhtmltopdf/**</exclude>
                    <exclude>EmojiReference.txt</exclude>
                    <exclude>java_model/**</exclude>
                    <exclude>io/netty/**</exclude>
                    <exclude>ai/grazie/**</exclude>
                    <exclude>org/eclipse/**</exclude>
                    <exclude>com/amazon/**</exclude>
                    <exclude>org/jdesktop/**</exclude>
                    <exclude>resources/event-log-metadata/**</exclude>
                    <exclude>win32-x86/**</exclude>
                    <exclude>win32-x86-64/**</exclude>
                    <exclude>com/intellij/xdebugger/**</exclude>
                    <exclude>com/intellij/collaboration/**</exclude>
                    <exclude>com/intellij/webSymbols/**</exclude>
                    <exclude>com/intellij/compiler/**</exclude>
                    <exclude>com/openhtmltopdf/**</exclude>
                    <exclude>com/thoughtworks/**</exclude>
                    <exclude>com/vladsch/**</exclude>
                    <exclude>com/intellij/workspaceModel/**</exclude>
                    <exclude>org/apache/http/**</exclude>
                    <exclude>org/apache/maven/**</exclude>
                    <exclude>org/apache/velocity/**</exclude>
                    <exclude>org/mozilla/**</exclude>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>com/intellij/ide/actions/**</exclude>
                    <exclude>com/intellij/ide/ui/**</exclude>
                    <exclude>com/intellij/ide/wizard/**</exclude>
                    <exclude>com/intellij/ide/browsers/**</exclude>
                    <exclude>com/intellij/ide/todo/**</exclude>
                    <exclude>com/intellij/ide/projectView/**</exclude>
                    <exclude>com/intellij/ide/favoritesTreeView/**</exclude>
                    <exclude>com/intellij/ide/hierarchy/**</exclude>
                    <exclude>com/intellij/ide/dnd/**</exclude>
                    <exclude>com/intellij/ui/treeStructure/**</exclude>
                    <exclude>com/intellij/ui/speedSearch/**</exclude>
                    <exclude>com/intellij/ui/tabs/**</exclude>
                    <exclude>com/intellij/ui/popup/**</exclude>
                    <exclude>com/intellij/ui/tree/**</exclude>
                    <exclude>com/intellij/util/ui/tree/**</exclude>
                    <exclude>com/intellij/notification/**</exclude>
                    <exclude>com/intellij/refactoring/**</exclude>
                    <exclude>com/intellij/find/**</exclude>
                    <exclude>com/intellij/usages/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/inspections/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/quickfix/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/refactoring/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/completion/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/navigation/**</exclude>
                    <exclude>org/jetbrains/kotlin/nj2k/**</exclude>
                    <exclude>org/jetbrains/kotlin/tools/**</exclude>
                    <exclude>inspectionDescriptions/**</exclude>
                    <exclude>intentionDescriptions/**</exclude>
                    <exclude>postfixTemplates/**</exclude>
                    <exclude>liveTemplates/**</exclude>
                    <exclude>fileTemplates/**</exclude>
                    <exclude>META-INF/services/org.codehaus.**</exclude>
                    <exclude>META-INF/services/javax.**</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>com/siyeh/**</exclude>
                    <exclude>fleet/**</exclude>
                    <exclude>andel/**</exclude>
                    <exclude>jetbrains/buildServer/**</exclude>
                    <exclude>standardSchemas/**</exclude>
                    <exclude>com/jgoodies/**</exclude>
                    <exclude>org/freedesktop/**</exclude>
                    <exclude>kotlin/script/**</exclude>
                    <exclude>kotlin/metadata/**</exclude>
                    <exclude>META-INF/native-image/**</exclude>
                    <exclude>META-INF/maven/**</exclude>
                    <exclude>okhttp3/**</exclude>
                    <exclude>okio/**</exclude>
                    <exclude>org/jetbrains/kotlin/j2k/**</exclude>
                    <exclude>org/jetbrains/kotlin/konan/**</exclude>
                    <exclude>org/jetbrains/kotlin/cli/**</exclude>
                    <exclude>org/jetbrains/kotlin/daemon/**</exclude>
                    <exclude>org/jetbrains/kotlin/gradle/**</exclude>
                    <exclude>org/jetbrains/kotlin/scripting/**</exclude>
                    <exclude>org/jetbrains/kotlin/buildtools/**</exclude>
                    <exclude>org/jetbrains/kotlin/build/**</exclude>
                    <exclude>org/jetbrains/kotlin/statistics/**</exclude>
                    <exclude>org/jetbrains/kotlin/onboarding/**</exclude>
                    <exclude>org/jetbrains/kotlin/incremental/**</exclude>
                    <exclude>org/jetbrains/builtInWebServer/**</exclude>
                    <exclude>org/jetbrains/eval4j/**</exclude>
                    <exclude>org/jetbrains/zip/**</exclude>
                    <exclude>org/jetbrains/io/**</exclude>
                    <exclude>com/intellij/internal/**</exclude>
                    <exclude>com/intellij/diagnostic/logging/**</exclude>
                    <exclude>com/intellij/diagnostic/report/**</exclude>
                    <exclude>com/intellij/microservices/**</exclude>
                    <exclude>com/intellij/remoteDev/**</exclude>
                    <exclude>com/intellij/remoteServer/**</exclude>
                    <exclude>com/intellij/designer/**</exclude>
                    <exclude>com/intellij/build/**</exclude>
                    <exclude>com/intellij/toolWindow/**</exclude>
                    <exclude>com/intellij/packaging/**</exclude>
                    <exclude>com/intellij/jarRepository/**</exclude>
                    <exclude>com/intellij/facet/**</exclude>
                    <exclude>com/intellij/credentialStore/**</exclude>
                    <exclude>com/intellij/framework/**</exclude>
                    <exclude>com/intellij/packageDependencies/**</exclude>
                    <exclude>com/intellij/largeFilesEditor/**</exclude>
                    <exclude>com/intellij/remote/**</exclude>
                    <exclude>com/intellij/testIntegration/**</exclude>
                    <exclude>com/intellij/terminal/**</exclude>
                    <exclude>com/intellij/slicer/**</exclude>
                    <exclude>com/intellij/tools/**</exclude>
                    <exclude>com/intellij/codeInspection/dataFlow/**</exclude>
                    <exclude>com/intellij/codeInspection/bytecodeAnalysis/**</exclude>
                    <exclude>com/intellij/codeInspection/streamMigration/**</exclude>
                    <exclude>com/intellij/codeInspection/streamToLoop/**</exclude>
                    <exclude>com/intellij/codeInspection/optionalToIf/**</exclude>
                    <exclude>com/intellij/codeInspection/deadCode/**</exclude>
                    <exclude>com/intellij/codeInspection/classCanBeRecord/**</exclude>
                    <exclude>com/intellij/codeInspection/java19api/**</exclude>
                    <exclude>com/intellij/codeInspection/java18api/**</exclude>
                    <exclude>com/intellij/platform/eel/**</exclude>
                    <exclude>com/intellij/platform/ijent/**</exclude>
                    <exclude>com/intellij/platform/feedback/**</exclude>
                    <exclude>com/intellij/platform/pasta/**</exclude>
                    <exclude>com/intellij/platform/templates/**</exclude>
                    <exclude>com/intellij/platform/externalSystem/**</exclude>
                    <exclude>com/intellij/ui/jcef/**</exclude>
                    <exclude>com/intellij/ui/mac/**</exclude>
                    <exclude>com/intellij/ui/icons/**</exclude>
                    <exclude>com/intellij/ui/colorpicker/**</exclude>
                    <exclude>com/intellij/ui/charts/**</exclude>
                    <exclude>com/intellij/ui/svg/**</exclude>
                    <exclude>com/intellij/ui/debugger/**</exclude>
                    <exclude>com/intellij/ui/codeFloatingToolbar/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/debugger/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/j2k/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/gradleJava/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/gradle/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/compilerPlugin/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/ultimate/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/search/**</exclude>
                    <exclude>org/jetbrains/kotlin/idea/actions/**</exclude>
                    <exclude>com/intellij/openapi/externalSystem/**</exclude>
                    <exclude>com/intellij/openapi/wm/impl/**</exclude>
                    <exclude>com/intellij/openapi/updateSettings/**</exclude>
                    <exclude>com/intellij/openapi/keymap/**</exclude>
                    <exclude>com/intellij/openapi/fileChooser/**</exclude>
                    <exclude>org/jetbrains/kotlin/analysis/decompiler/**</exclude>
                    <exclude>org/jetbrains/kotlin/analysis/decompiled/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/mvc/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/compiler/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/shell/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/debugger/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/refactoring/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/template/**</exclude>
                    <exclude>org/jetbrains/plugins/groovy/actions/**</exclude>
                    <exclude>com/intellij/java/debugger/**</exclude>
                    <exclude>com/intellij/java/performancePlugin/**</exclude>
                    <exclude>com/intellij/java/terminal/**</exclude>
                    <exclude>com/intellij/java/ultimate/**</exclude>
                    <exclude>com/intellij/java/execution/**</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <mainClass>com.intellij.formatter.JetbrainsFormatterApplication</mainClass>
          <classpathScope>compile</classpathScope>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
